## Alchemy

In [1]:
# Jupyter cell: Initialize and optimize SQLite in FLY

# 1) Imports
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from infrastructure.config import Config

In [1]:
# 2) Load application configuration
#    Adjust constructor as needed (e.g., passing path to config file or env vars)
config = Config()

NameError: name 'Config' is not defined

In [ ]:
# 3) Create the SQLAlchemy engine with thread-safe and future settings
engine = create_engine(
    config.database.connection_string,
    connect_args={"check_same_thread": False},  # allow multi-thread access
    future=True,
)

In [ ]:
# 4) Execute SQLite PRAGMAs for performance & integrity
with engine.connect() as conn:  # type: ignore
    conn.execute(text("PRAGMA wal_checkpoint"))  # type: ignore

    # ou, se preferir garantir que todo o WAL seja aplicado e truncado:
    conn.execute(text("PRAGMA wal_checkpoint(FULL)"))  # type: ignore
    conn.execute(text("PRAGMA wal_checkpoint(RESTART)"))  # type: ignore
    conn.execute(text("PRAGMA wal_checkpoint(TRUNCATE)"))  # type: ignore
    conn.execute(text("PRAGMA optimize"))  # type: ignore # Run internal optimizations
    conn.execute(text("PRAGMA journal_mode=WAL"))  # type: ignore # Write-Ahead Logging
    conn.execute(text("PRAGMA synchronous=FULL"))  # type: ignore # Full disk sync for safety
    conn.execute(text("PRAGMA foreign_keys=ON"))  # type: ignore # Enforce FK constraints
    conn.execute(text("PRAGMA temp_store=MEMORY"))  # type: ignore # RAM for temp tables
    conn.execute(text("PRAGMA cache_size=-65536"))  # type: ignore # 64 MB cache

In [ ]:
# 5) Create a session factory for ORM transactions
Session = sessionmaker(  # type: ignore
    bind=engine,  # type: ignore
    autoflush=True,
    expire_on_commit=True,
)

In [ ]:
# 6) (Optional) Inspect existing tables
with Session() as session:  # type: ignore
    result = session.execute(text("SELECT name FROM sqlite_master WHERE type='table';"))  # type: ignore
    tables = [row[0] for row in result]
    print("⏺️ Tables in database:", tables)

## YFINANCE

In [33]:
import yfinance as yf

tickers = ["LREN3.SA", "VALE3.SA"]

# Histórico diário
df = yf.download(tickers, start="1960-01-01", interval="1d",)

C:\Users\faust\AppData\Local\Temp\ipykernel_17748\3791307439.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers, start="1960-01-01", interval="1d",)
[*********************100%***********************]  2 of 2 completed

In [34]:
df

Price             Close                    High                     Low  \
Ticker         LREN3.SA   VALE3.SA     LREN3.SA   VALE3.SA     LREN3.SA
Date
2000-01-03          NaN   1.389175          NaN   1.406043          NaN
2000-01-04  5443.398926   1.356099  8467.510075   1.378921  5443.398926
2000-01-05  5443.398926   1.356099  5443.398926   1.356099  5443.398926
2000-01-06  5443.398926   1.356099  5443.398926   1.389174  5443.398926
2000-01-07  5443.398926   1.405712  5443.398926   1.412658  5443.398926
...                 ...        ...          ...        ...          ...
2025-09-15    16.219999  57.500000    16.260000  57.549999    15.950000
2025-09-16    16.900000  57.700001    17.090000  58.060001    16.350000
2025-09-17    17.020000  57.799999    17.540001  58.020000    16.790001
2025-09-18    17.049999  57.689999    17.150000  58.080002    16.940001
2025-09-19    16.920000  57.919998    17.180000  58.189999    16.870001

Price                         Open                 Volume
Ticker       VALE3.SA     LREN3.SA   VALE3.SA    LREN3.SA  VALE3.SA
Date
2000-01-03   1.389175          NaN   1.389175         NaN    585600
2000-01-04   1.356099  8467.510075   1.375944         0.0    782400
2000-01-05   1.339561  5443.398926   1.339561         0.0   1876800
2000-01-06   1.356099  5443.398926   1.356099         0.0    792000
2000-01-07   1.372636  5443.398926   1.372636         0.0   5347200
...               ...          ...        ...         ...       ...
2025-09-15  56.980000    15.950000  57.480000  14180200.0  12457500
2025-09-16  57.189999    16.350000  57.770000  19329800.0  15618500
2025-09-17  57.360001    17.010000  57.540001  31079600.0  23116700
2025-09-18  57.400002    17.040001  57.840000   8975200.0  17700400
2025-09-19  57.549999    17.139999  57.970001  15882500.0  25374600

[6458 rows x 10 columns]

### Preço atual e variação intraday

In [9]:
info = yf.Tickers(" ".join(tickers))

for t in tickers:
    data = info.tickers[t].info
    print(
        t,
        "Preço:", data.get("regularMarketPrice"),
        "Variação:", data.get("regularMarketChange"),
        "Variação %:", data.get("regularMarketChangePercent"),
    )

LREN3.SA Preço: 16.92 Variação: -0.12999916 Variação %: -0.76245844
VALE3.SA Preço: 57.92 Variação: 0.22999954 Variação %: 0.39868182

### Dados fundamentais

In [10]:
data = {}

for t in tickers:
    tk = yf.Ticker(t)
    info = tk.info
    data[t] = {
        "Nome": info.get("longName"),
        "Setor": info.get("sector"),
        "Indústria": info.get("industry"),
        "Valor de Mercado": info.get("marketCap"),
        "P/L": info.get("trailingPE"),
        "Lucro por Ação (EPS)": info.get("trailingEps"),
        "Dividend Yield": info.get("dividendYield"),
        "Beta": info.get("beta"),
        "Moeda": info.get("currency"),
    }

import pandas as pd
df = pd.DataFrame(data).T
df

,Nome,Setor,Indústria,Valor de Mercado,P/L,Lucro por Ação (EPS),Dividend Yield,Beta,Moeda
LREN3.SA,Lojas Renner S.A.,Consumer Cyclical,Department Stores,16776969216,12.916031,1.31,5.19,0.593,BRL
VALE3.SA,Vale S.A.,Basic Materials,Other Industrial Metals & Mining,247247650816,8.938272,6.48,11.48,1.039,BRL

In [16]:

t = yf.Ticker("VAle3.SA")

# Retorna todos os campos de fundamentos
info = t.info

# Converter para DataFrame para melhor leitura
df = pd.DataFrame(info.items(), columns=["Campo", "Valor"])
df

                        Campo                                      Valor
0                    address1                          Praia de Botafogo
1                    address2  186 offices 1101, 1701, and 1801 Botafogo
2                        city                             Rio De Janeiro
3                       state                                         RJ
4                         zip                                  22250-145
..                        ...                                        ...
158  earningsCallTimestampEnd                                 1754056800
159    isEarningsDateEstimate                                      False
160   epsTrailingTwelveMonths                                       6.48
161                epsForward                                      11.94
162          trailingPegRatio                                     8.2203

[163 rows x 2 columns]

### Dados financeiros estruturados

In [18]:
import yfinance as yf

tickers = ["LREN3.SA"]

for t in tickers:
    tk = yf.Ticker(t)

    print(f"\n--- {t} ---")

    # Demonstrativos de resultado (anual e trimestral)
    print("Income Statement (anual):")
    print(tk.financials)

    print("\nIncome Statement (trimestral):")
    print(tk.quarterly_financials)

    # Balanço patrimonial
    print("\nBalance Sheet (anual):")
    print(tk.balance_sheet)

    print("\nBalance Sheet (trimestral):")
    print(tk.quarterly_balance_sheet)

    # Fluxo de caixa
    print("\nCashflow (anual):")
    print(tk.cashflow)

    print("\nCashflow (trimestral):")
    print(tk.quarterly_cashflow)

--- LREN3.SA ---
Income Statement (anual):
                                                      2024-12-31  \
Tax Effect Of Unusual Items                        -1.025383e+08
Tax Rate For Calcs                                  9.410000e-02
Normalized EBITDA                                   3.972445e+09
Total Unusual Items                                -1.089674e+09
Total Unusual Items Excluding Goodwill             -1.089674e+09
Net Income From Continuing Operation Net Minori...  1.196668e+09
Reconciled Depreciation                             1.244254e+09
Reconciled Cost Of Revenue                          5.694417e+09
EBITDA                                              2.882771e+09
EBIT                                                1.638517e+09
Net Interest Income                                -5.202990e+08
Interest Expense                                    3.175200e+08
Interest Income                                     3.124010e+08
Normalized Income                                   2.183804e+09
Net Income From Continuing And Discontinued Ope...  1.196668e+09
Total Expenses                                      1.147752e+10
Rent Expense Supplemental                           4.505660e+08
Total Operating Income As Reported                           NaN
Diluted Average Shares                              1.051732e+09
Basic Average Shares                                1.051732e+09
Diluted EPS                                         1.137837e+00
Basic EPS                                           1.137837e+00
Diluted NI Availto Com Stockholders                 1.196668e+09
Net Income Common Stockholders                      1.196668e+09
Otherunder Preferred Stock Dividend                 0.000000e+00
Net Income                                          1.196668e+09
Net Income Including Noncontrolling Interests       1.196668e+09
Net Income Continuous Operations                    1.196668e+09
Tax Provision                                       1.243290e+08
Pretax Income                                       1.320997e+09
Special Income Charges                             -1.100617e+09
Write Off                                           9.572800e+08
Impairment Of Capital Assets                        1.433370e+08
Net Non Operating Interest Income Expense          -5.202990e+08
Total Other Finance Cost                            5.151800e+08
Interest Expense Non Operating                      3.175200e+08
Interest Income Non Operating                       3.124010e+08
Operating Income                                    2.958845e+09
Operating Expense                                   5.783104e+09
Other Operating Expenses                            3.371700e+07
Depreciation And Amortization In Income Statement   1.197844e+09
Depreciation Income Statement                       1.197844e+09
Selling General And Administration                  2.021453e+09
Selling And Marketing Expense                       1.557934e+09
General And Administrative Expense                  4.635190e+08
Rent And Landing Fees                               4.505660e+08
Gross Profit                                        8.741949e+09
Cost Of Revenue                                     5.694417e+09
Total Revenue                                       1.443637e+10
Operating Revenue                                   1.443637e+10

                                                      2023-12-31  \
Tax Effect Of Unusual Items                        -5.044233e+08
Tax Rate For Calcs                                  3.400000e-01
Normalized EBITDA                                   3.818904e+09
Total Unusual Items                                -1.483598e+09
Total Unusual Items Excluding Goodwill             -1.483598e+09
Net Income From Continuing Operation Net Minori...  9.762590e+08
Reconciled Depreciation                             1.098363e+09
Reconciled Cost Of Revenue                          5.427247e+09
EBITDA                                              2.335306e+09
EBIT                                                1.236943e+09
Net Interest Income                                -5.507510e+08
Interest Expense                                    3.962760e+08
Interest Income                                     4.092980e+08
Normalized Income                                   1.955434e+09
Net Income From Continuing And Discontinued Ope...  9.762590e+08
Total Expenses                                      1.068874e+10
Rent Expense Supplemental                           4.330370e+08
Total Operating Income As Reported                           NaN
Diluted Average Shares                              1.057702e+09
Basic Average Shares                                1.054573e+09
Diluted EPS                                         9.230000e-01
Basic EPS                                           9.257000e-01
Diluted NI Availto Com Stockholders                 9.762590e+08
Net Income Common Stockholders                      9.762590e+08
Otherunder Preferred Stock Dividend                 0.000000e+00
Net Income                                          9.762590e+08
Net Income Including Noncontrolling Interests       9.762590e+08
Net Income Continuous Operations                    9.762590e+08
Tax Provision                                      -1.355920e+08
Pretax Income                                       8.406670e+08
Special Income Charges                             -1.484119e+09
Write Off                                           1.343277e+09
Impairment Of Capital Assets                        1.408420e+08
Net Non Operating Interest Income Expense          -5.507510e+08
Total Other Finance Cost                            5.637730e+08
Interest Expense Non Operating                      3.962760e+08
Interest Income Non Operating                       4.092980e+08
Operating Income                                    2.959109e+09
Operating Expense                                   5.261493e+09
Other Operating Expenses                            2.044900e+07
Depreciation And Amortization In Income Statement   1.050242e+09
Depreciation Income Statement                       1.050242e+09
Selling General And Administration                  1.921353e+09
Selling And Marketing Expense                       1.499147e+09
General And Administrative Expense                  4.222060e+08
Rent And Landing Fees                               4.330370e+08
Gross Profit                                        8.220602e+09
Cost Of Revenue                                     5.427247e+09
Total Revenue                                       1.364785e+10
Operating Revenue                                   1.364785e+10

                                                      2022-12-31  \
Tax Effect Of Unusual Items                        -6.887000e+07
Tax Rate For Calcs                                  6.690000e-02
Normalized EBITDA                                   3.997889e+09
Total Unusual Items                                -1.029447e+09
Total Unusual Items Excluding Goodwill             -1.029447e+09
Net Income From Continuing Operation Net Minori...  1.291704e+09
Reconciled Depreciation                             1.041025e+09
Reconciled Cost Of Revenue                          5.286323e+09
EBITDA                                              2.968442e+09
EBIT                                                1.927417e+09
Net Interest Income                                -4.713460e+08
Interest Expense                                    5.431320e+08
Interest Income                                     5.485920e+08
Normalized Income                                   2.252281e+09
Net Income From Continuing And Discontinued Ope...  1.291704e+09
Total Expenses                                      1.032449e+10
Rent Expense Supplemental                           4.361180e+08
Total Operating Income As Reported                  1.407401e+09
Diluted Average Shares                              1.073898e+09
Basic Average Shares                                1.071494e+09
Diluted EPS                                         1.202818e+00
Basic EPS                                           1.205545e+00
Diluted NI Availto Com Stockholders                 1.291704e+09
Net Income Common Stockholders                      1.291704e+09
Otherunder Preferred Stock Dividend                 0.000000e+00
Net Income                                          1.291704e+09
Net Income Including Noncontrolling Interests       1.291704e+09
Net Income Continuous Operations                    1.291704e+09
Tax Provision                                       9.258100e+07
Pretax Income                                       1.384285e+09
Special Income Charges                             -1.029447e+09
Write Off                                           9.917420e+08
Impairment Of Capital Assets                        3.770500e+07
Net Non Operating Interest Income Expense          -4.713460e+08
Total Other Finance Cost                            4.768060e+08
Interest Expense Non Operating                      5.431320e+08
Interest Income Non Operating                       5.485920e+08
Operating Income                                    2.946643e+09
Operating Expense                                   5.038171e+09
Other Operating Expenses                            5.097950e+08
Depreciation And Amortization In Income Statement   9.938500e+08
Depreciation Income Statement                       9.938500e+08
Selling General And Administration                  1.797242e+09
Selling And Marketing Expense                       1.399739e+09
General And Administrative Expense                  3.975030e+08
Rent And Landing Fees                               4.361180e+08
Gross Profit                                        7.984814e+09
Cost Of Revenue                                     5.286323e+09
Total Revenue                                       1.327114e+10
Operating Revenue                                   1.327114e+10

                                                      2021-12-31   2020-12-31
Tax Effect Of Unusual Items                        -3.662348e+06          NaN
Tax Rate For Calcs                                  1.050000e-02          NaN
Normalized EBITDA                                   2.276432e+09          NaN
Total Unusual Items                                -3.487950e+08          NaN
Total Unusual Items Excluding Goodwill             -3.487950e+08          NaN
Net Income From Continuing Operation Net Minori...  6.331120e+08          NaN
Reconciled Depreciation                             9.160700e+08          NaN
Reconciled Cost Of Revenue                          4.399178e+09          NaN
EBITDA                                              1.927637e+09          NaN
EBIT                                                1.011567e+09          NaN
Net Interest Income                                -5.396170e+08          NaN
Interest Expense                                    3.717140e+08          NaN
Interest Income                                     2.230900e+08          NaN
Normalized Income                                   9.782447e+08          NaN
Net Income From Continuing And Discontinued Ope...  6.331120e+08          NaN
Total Expenses                                      9.004384e+09          NaN
Rent Expense Supplemental                           3.918540e+08          NaN
Total Operating Income As Reported                  8.139440e+08  856879000.0
Diluted Average Shares                              1.050729e+09          NaN
Basic Average Shares                                1.047694e+09          NaN
Diluted EPS                                         6.025450e-01          NaN
Basic EPS                                           6.042730e-01          NaN
Diluted NI Availto Com Stockholders                 6.331120e+08          NaN
Net Income Common Stockholders                      6.331120e+08          NaN
Otherunder Preferred Stock Dividend                 0.000000e+00          NaN
Net Income                                          6.331120e+08          NaN
Net Income Including Noncontrolling Interests       6.331120e+08          NaN
Net Income Continuous Operations                    6.331120e+08          NaN
Tax Provision                                       6.741000e+06          NaN
Pretax Income                                       6.398530e+08          NaN
Special Income Charges                             -3.487950e+08          NaN
Write Off                                           3.398010e+08          NaN
Impairment Of Capital Assets                        8.994000e+06          NaN
Net Non Operating Interest Income Expense          -5.396170e+08          NaN
Total Other Finance Cost                            3.909930e+08          NaN
Interest Expense Non Operating                      3.717140e+08          NaN
Interest Income Non Operating                       2.230900e+08          NaN
Operating Income                                    1.567182e+09          NaN
Operating Expense                                   4.605206e+09          NaN
Other Operating Expenses                            3.808000e+07          NaN
Depreciation And Amortization In Income Statement   8.770170e+08          NaN
Depreciation Income Statement                       8.770170e+08          NaN
Selling General And Administration                  1.571964e+09          NaN
Selling And Marketing Expense                       1.274801e+09          NaN
General And Administrative Expense                  2.971630e+08          NaN
Rent And Landing Fees                               3.918540e+08          NaN
Gross Profit                                        6.172388e+09          NaN
Cost Of Revenue                                     4.399178e+09          NaN
Total Revenue                                       1.057157e+10          NaN
Operating Revenue                                   1.057157e+10          NaN

Income Statement (trimestral):
                                                      2025-06-30  \
Tax Effect Of Unusual Items                        -5.395131e+07
Tax Rate For Calcs                                  2.100000e-01
Normalized EBITDA                                   1.165520e+09
Total Unusual Items                                -2.569110e+08
Total Unusual Items Excluding Goodwill             -2.569110e+08
Net Income From Continuing Operation Net Minori...  4.044960e+08
Reconciled Depreciation                             3.345690e+08
Reconciled Cost Of Revenue                          1.563766e+09
EBITDA                                              9.086090e+08
EBIT                                                5.740400e+08
Net Interest Income                                -2.086660e+08
Interest Expense                                    6.198900e+07
Interest Income                                     2.749300e+07
Normalized Income                                   6.074557e+08
Net Income From Continuing And Discontinued Ope...  4.044960e+08
Total Expenses                                      3.207888e+09
Rent Expense Supplemental                           1.310770e+08
Total Operating Income As Reported                           NaN
Diluted Average Shares                              1.005208e+09
Basic Average Shares                                1.005208e+09
Diluted EPS                                         3.999000e-01
Basic EPS                                           4.024000e-01
Diluted NI Availto Com Stockholders                 4.044960e+08
Net Income Common Stockholders                      4.044960e+08
Otherunder Preferred Stock Dividend                 0.000000e+00
Net Income                                          4.044960e+08
Net Income Including Noncontrolling Interests       4.044960e+08
Net Income Continuous Operations                    4.044960e+08
Tax Provision                                       1.075550e+08
Pretax Income                                       5.120510e+08
Other Non Operating Income Expenses                          NaN
Special Income Charges                             -2.570630e+08
Write Off                                           2.557350e+08
Impairment Of Capital Assets                        1.328000e+06
Net Non Operating Interest Income Expense          -2.086660e+08
Total Other Finance Cost                            1.741700e+08
Interest Expense Non Operating                      6.198900e+07
Interest Income Non Operating                       2.749300e+07
Operating Income                                    9.596780e+08
Operating Expense                                   1.644122e+09
Other Operating Expenses                            1.878400e+07
Depreciation And Amortization In Income Statement   3.230730e+08
Depreciation Income Statement                       3.230730e+08
Selling General And Administration                  5.607160e+08
Selling And Marketing Expense                       4.299850e+08
General And Administrative Expense                  1.307310e+08
Rent And Landing Fees                               1.310770e+08
Gross Profit                                        2.603800e+09
Cost Of Revenue                                     1.563766e+09
Total Revenue                                       4.167566e+09
Operating Revenue                                   4.167566e+09

                                                      2025-03-31  \
Tax Effect Of Unusual Items                        -2.376025e+07
Tax Rate For Calcs                                  1.316000e-01
Normalized EBITDA                                   8.242730e+08
Total Unusual Items                                -1.805490e+08
Total Unusual Items Excluding Goodwill             -1.805490e+08
Net Income From Continuing Operation Net Minori...  2.210330e+08
Reconciled Depreciation                             3.164630e+08
Reconciled Cost Of Revenue                          1.236106e+09
EBITDA                                              6.437240e+08
EBIT                                                3.272610e+08
Net Interest Income                                -1.526690e+08
Interest Expense                                    7.273900e+07
Interest Income                                     4.785000e+07
Normalized Income                                   3.778218e+08
Net Income From Continuing And Discontinued Ope...  2.210330e+08
Total Expenses                                      2.668538e+09
Rent Expense Supplemental                           1.159970e+08
Total Operating Income As Reported                           NaN
Diluted Average Shares                              1.046558e+09
Basic Average Shares                                1.041346e+09
Diluted EPS                                         2.112000e-01
Basic EPS                                           2.123000e-01
Diluted NI Availto Com Stockholders                 2.210330e+08
Net Income Common Stockholders                      2.210330e+08
Otherunder Preferred Stock Dividend                 0.000000e+00
Net Income                                          2.210330e+08
Net Income Including Noncontrolling Interests       2.210330e+08
Net Income Continuous Operations                    2.210330e+08
Tax Provision                                       3.348900e+07
Pretax Income                                       2.545220e+08
Other Non Operating Income Expenses                          NaN
Special Income Charges                             -1.807040e+08
Write Off                                           1.771410e+08
Impairment Of Capital Assets                        3.563000e+06
Net Non Operating Interest Income Expense          -1.526690e+08
Total Other Finance Cost                            1.277800e+08
Interest Expense Non Operating                      7.273900e+07
Interest Income Non Operating                       4.785000e+07
Operating Income                                    5.890380e+08

In [28]:
tk.eps_revisions

        upLast7days  upLast30days  downLast30days  downLast7Days
period
0q                0             0               2              0
+1q               0             1               1              0
0y                1             3               4              0
+1y               1             2               5              3